# Generated by Django 5.2 on 2025-05-07 03:38

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
