# Generated by Django 5.2 on 2025-05-07 04:08

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
