# Generated by Django 5.0.4 on 2024-04-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temphumiditysensor',
            name='temp_fahrenheit',
            field=models.FloatField(blank=True, null=True, verbose_name='Temperature in Fahrenheit'),
        ),
    ]
