# Generated by Django 5.0.4 on 2024-04-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TempHumidity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('temp_c', models.FloatField(verbose_name='Temperature in Celsius')),
                ('rel_humidity', models.FloatField(verbose_name='Relative Humidity in %')),
                ('read_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Temperature and Humidity',
                'verbose_name_plural': 'Temperature and Humidity Readings',
                'db_table': 'temp_humidity',
                'managed': False,
            },
        ),
    ]
