# Generated by Django 5.2.4 on 2025-07-13 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0006_project_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('content', models.TextField(help_text='The main content of the log entry. Markdown is supported.')),
                ('published_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dev_log_entries', to='projects.project')),
            ],
            options={
                'ordering': ('-published_date',),
            },
        ),
    ]
