# Generated by Django 5.2.4 on 2025-07-16 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_log', '0002_alter_devlogentry_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devlogentry',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
