# Generated by Django 5.0.6 on 2024-05-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0002_certification_skills_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
